language: ruby
rvm:
  - '1.8.7'
  - '1.9.2'
  - '1.9.3'
  - '2.0.0'
gemfile:
  - gemfiles/rails3_1_10.gemfile
  - gemfiles/rails3_2_11.gemfile
  - gemfiles/rails4.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails4.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile
